api_login_check:
    path: /api/login_check
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc
app:
    type:     rest
    prefix:   /api
    resource: "@AppBundle/Resources/config/api-routing.yml"
test: 
    resource: "@AppBundle/Controller/TestController.php"
    type:     annotation
    prefix:   /test

